data real
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (1,'1101233465', 2016, 1, 'SISTEM INFORMASI KREDIT BARANG RUMAH TANGGA', False
,False
,False
,4);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (2,'1235879854', 2016, 2, 'PROGRAM BANTU PENENTUAN PLAFON PINJAMAN PELANGGAN BERDASARKAN RIWAYAT OMSET DAN KREDIBILITAS PEMBAYARAN', False
,False
,False
,7);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (3,'1666343272', 2015, 2, ' TOP-N ANALISIS UNTUK SISTEM INFORMASI RENTAL VCD            ', False
,False
,False
,5);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (4,'1263462118', 2016, 2, ' SISTEM INFORMASI BISNIS BIRO PERJALANAN DAN PENGIRIMAN PAKET', False
,False
,False
,2);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (5,'1515042382', 2015, 2, ' PROGRAM TRANSFER TEKS PADA KASUS PENGOLAHAN DATA BARANG', False
,False
,False
,5);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (6,'1317117459', 2015, 1, 'PROGRAM BANTU KONTROL BAHAN BANGUNAN PERUSAHAAN PROPERTY', False
,False
,False
,3);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (7,'1522292755', 2015, 1, 'PROGRAM BANTU PENGAMBILAN KEPUTUSAN PEMBELIAN INVENTARIS GEREJA', False
,False
,False
,7);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (8,'1433844207', 2016, 2, 'PERBANDINGAN RIP DENGAN IGRP', False
,False
,False
,3);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (9,'1409155433', 2016, 1, 'PROGRAM BANTU DOKUMENTASI KOMENTAR UNTUK PENILAIAN SISWA SEKOLAH DASAR', False
,False
,False
,9);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (10,'1194658865', 2015, 1, 'SISTEM INFORMASI PENJUALAN TIKET BUS AKAP DENGAN PENDEKATAN METODE CRM', False
,False
,False
,2);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (11,'1429648330', 2016, 1, 'PENAJAMAN CITRA TEREKAM STASIUN TELEVISI DENGAN METODE LAPLACIAN', False
,False
,False
,6);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (12,'1660561113', 2015, 2, 'SISTEM PENDUKUNG PROSES KENDALI PADA TRANSAKSI RENTAL VCD MULTIUSER', False
,False
,False
,2);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (13,'1609260311', 2015, 2, 'PROGRAM BANTU UNTUK MENGETAHUI SUASANA HATI (MOOD) MANUSIA DENGAN OXFORD HAPPINESS INVENTORY (OHI)', False
,False
,False
,1);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (14,'1307370680', 2016, 2, 'PENERAPAN TRACK EDITING RECORD PADA SISTEM INFORMASI PENDATAAN JEMAAT', False
,False
,False
,3);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (15,'1577759523', 2016, 1, 'ADAPTIVE NEURO FUZZY INFERENCE SISTEM UNTUK PENGENALAN POLA HURUF KAPITAL', False
,False
,False
,5);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (16,'1417424826', 2015, 1, 'PROGRAM BANTU MENGUBAH EKSPRESI WAJAH MANUSIA DENGAN MENGGUNAKAN FACIAL IMAGE WARPING', False
,False
,False
,8);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (17,'1398377479', 2016, 2, 'PERBANDINGAN ELIMINASI NOISE DENGAN GAUSSIAN SMOOTHING DAN MASK MEDIAN', False
,False
,False
,4);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (18,'1273884833', 2016, 2, 'PERBANDINGAN EDGE DETECTION MENGGUNAKAN OPERATOR ISOTROPIK DAN OPERATOR STOKASTIK', False
,False
,False
,2);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (19,'1542830049', 2016, 2, 'IMPLEMENTASI “DEMPSTER SHAFER” UNTUK PENCARIAN JENIS PENYAKIT THT', False
,False
,False
,5);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (20,'1217272787', 2015, 1, 'PROGRAM BANTU ANALISIS KESEHATAN IBU DAN ANAK (KIA) DENGAN MODEL PWS-KIA DAN METODE BACKPROPAGATION', False
,False
,False
,9);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (21,'1580703554', 2016, 2, 'TEKNIK THINNING DENGAN ALGORITMA NANGENDRAPRASAD-WANG-GUPTA', False
,False
,False
,3);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (22,'1186682932', 2015, 2, 'BLUR DAN DEBLURRING DENGAN MENGGUNAKAN METODE REGURALIZED FILTER ', False
,False
,False
,5);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (23,'1632548402', 2015, 1, 'IMPLEMENTASI OPENLASZLO UNTUK APLIKASI WEB PORTAL ', False
,False
,False
,4);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (24,'1210045022', 2016, 1, 'IMPLEMENTASI WEB SERVICE SEBAGAI EMAIL GATEWAY', False
,False
,False
,4);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (25,'1698878208', 2016, 2, 'PROGRAM BANTU PERINGKASAN DOKUMEN TEKS BERBAHASA INGGRIS DENGAN ALGORITMA PORTER STEMMING', False
,False
,False
,2);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (26,'1232963588', 2015, 2, 'IMPLEMENTASI METODE TF-IDF & K-MEANS UNTUK CLUSTERING DOKUMEN TEKS ', False
,False
,False
,5);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (27,'1106607723', 2015, 1, 'SISTEM NAVIGASI ROBOT MENGGUNAKAN SENSOR KOMPAS ANALOG DINSMORE 1655', False
,False
,False
,3);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (28,'1546087926', 2016, 2, 'ANALISA SPASIAL HUTAN DAN TUTUPAN LAHAN BERBASIS SISTEM INFORMASI GEOGRAFIS', False
,False
,False
,3);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (29,'1397972066', 2015, 2, 'PEMODELAN SIX-LEGGED ROBOT MENGGUNAKAN SENSOR SONAR SRF-04 UNTUK OBSTACLES AVOIDANCE SEBAGAI ALAT PERAGA PRAKTIKUM EKSPERIMENTAL ROBOTIKA', False
,False
,False
,6);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (30,'1283737835', 2015, 2, 'KOMPRESI CITRA DENGAN METODE FOUR LEVEL BLOCK TRUNCATION CODING', False
,False
,False
,6);"


data random

"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (31,'1573327482', 2016, 1, 'ALAT BANTU UNTUK MENGUKUR KOMPLEKSITAS ALIRAN
 DATA DARI SEBUAH PROGRAM MODULAR', False
,False
,False
,4);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (32,'1119639841', 2016, 2, 'SISTEM INFORMASI PENGONTROLAN
 SIRKULASI BARANG PERCETAKAN', False
,False
,False
,7);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (33,'1327929642', 2015, 2, 'SISTEM INFORMASI KEUANGAN GEREJA', False
,False
,False
,5);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (34,'1351935759', 2016, 2, 'PROGRAM BANTU PERAMALAN HARGA
 PENJUALAN HANDPHONE PADA PERIODE TERTENTU
 DENGAN METODE BROWNS', False
,False
,False
,2);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (35,'1247309979', 2015, 2, 'APLIKASI PEMBELAJARAN SISTEM
  TRANSPORTASI DAN PENGELUARAN PADA
 TUMBUHAN BERBASIS MULTIMEDIA', False
,False
,False
,5);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (36,'1585374542', 2015, 1, 'APLIKASI BRIEFCASE BERBASIS WEB DENGAN
 MENGGUNAKAN ASP.NET', False
,False
,False
,3);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (37,'1528257570', 2015, 1, 'PENENTUAN CHORD LAGU DENGAN MENGGUNAKAN
  DERAJAT SIMILARITAS', False
,False
,False
,7);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (38,'1607998556', 2016, 2, 'IMPLEMENTASI MVC FRAMEWORK PADA RAILS UNTUK APLIKASI WEB PORTAL', False
,False
,False
,3);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (39,'1536677306', 2016, 1, 'MEMBANDINGKAN METODE SEASONAL EXPONENTIAL SMOOTHING DAN METODE MOVING AVERAGE UNTUK MEMPREDIKSI PERMINTAAN REAGEN
 STUDI KASUS : “CV. BRYANLAB”', False
,False
,False
,9);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (40,'1674320163', 2015, 1, 'ANALISIS DAN PERBANDINGAN OPERASI MEDIAN PADA PROSES ELIMINASI DERAU MENGGUNAKAN MATRIKS 3X3, 5X5, 7X7, 9X9 DAN 11X11', False
,False
,False
,2);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (41,'1384533543', 2016, 1, 'PROGRAM MONITORING LINK PARTNER
  DENGAN MENGGUNAKAN FASILITAS SEARCH ENGINE', False
,False
,False
,6);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (42,'1675226975', 2015, 2, 'IMPLEMENTASI OPERASI CLOSING DAN OPENING PADA CITRA BINER', False
,False
,False
,2);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (43,'1160348169', 2015, 2, 'IMPLEMENTASI METODE NAÏVE BAYES DAN ID3 UNTUK
 MEMPREDIKSI HASIL PERTANDINGAN
 SEPAK BOLA LIGA INGGRIS', False
,False
,False
,1);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (44,'1562569885', 2016, 2, 'IMPLEMENTASI SAPI UNTUK MENJALANKAN
  PROGRAM APLIKASI', False
,False
,False
,3);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (45,'1607173974', 2016, 1, 'IMPLEMENTASI ASYNCHRONOUS METHOD CALL PADA RMI
 UNTUK GAME KOMPETISI BATTLESHIP', False
,False
,False
,5);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (46,'1595927636', 2015, 1, 'IMPLEMENTASI ADAPTIVE HUFFMAN TREE BERBASS KATA UNTUK PEMAMPATAN BERKAS TEKS BERBAHASA INDONESIA', False
,False
,False
,8);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (47,'1703928757', 2016, 2, 'IMPLEMENTASI ALGORITMA GENETIK DALAM PENDISTRIBUSIAN
 JADWAL KULIAH MAHASISWA', False
,False
,False
,4);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (48,'1482016529', 2016, 2, 'APLIKASI RSS NEWS READER PADA HANDPHONE', False
,False
,False
,2);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (49,'1304435203', 2016, 2, 'IMPLEMENTASI ALGORITMA KOLONI SEMUT UNTUK OPTIMALISASI SELEKSI TEMAN SEKAMAR', False
,False
,False
,5);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (50,'1342765290', 2015, 1, 'IMPLEMENTASI METODE STACK DAN ALGORITMA KNUTH MORRIS PRATT UNTUK JAVA TEXT EDITOR', False
,False
,False
,9);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (51,'1233364632', 2016, 2, 'PEMBUATAN KAMUS PELAFALAN
 KATA TAK BERIMBUHAN BAHASA INDONESIA DENGAN OTOMASI PEMENGGALAN SUKU KATA', False
,False
,False
,3);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (52,'1589554751', 2015, 2, 'APLIKASI PENDETEKSI GERAKAN MENGGUNAKAN WEBCAM UNTUK SEKURITAS RUANGAN', False
,False
,False
,5);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (53,'1399411709', 2015, 1, 'IMPLEMENTASI ALGORITMA ANT COLONY SYSTEM UNTUK MENENTUKAN RUTE WISATA DI PULAU JAWA BERBASIS
 SISTEM INFORMASI GEOGRAFIS', False
,False
,False
,4);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (54,'1166560861', 2016, 1, 'ANALISIS PERSEBARAN WARNET
 DI YOGYAKARTA BERBASIS SISTEM INFORMASI GEOGRAFIS', False
,False
,False
,4);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (55,'1514083484', 2016, 2, 'IMPLEMENTASI ANALISIS TRIGRAM 
 UNTUK MEMPERBAIKI KESALAHAN PENGEJAAN PADA DOKUMEN TEKS BAHASA INDONESIA', False
,False
,False
,2);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (56,'1395371332', 2015, 2, 'SISTEM INFORMASI GEOGRAFIS
 UNTUK LAMPU LALU LINTAS DI YOGYAKARTA', False
,False
,False
,5);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (57,'1261224600', 2015, 1, 'PENERAPAN METODE HYBRID DARI TERM WEIGHTING DALAM MELAKUKAN PENCARIAN PASAL KITAB UNDANG-UNDANG HUKUM PIDANA
 DENGAN KASUS PIDANA UMUM', False
,False
,False
,3);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (58,'1487221415', 2016, 2, 'PENERAPAN PHP GD LIBRARY
  UNTUK SISTEM INFORMASI GEOGRAFIS MODEL VEKTOR DI PROPINSI DIY', False
,False
,False
,3);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (59,'1414184009', 2015, 2, 'IMPLEMENTASI ALGORITMA SIMULATED ANNEALING DALAM PENYELESAIAN MASALAH PENJADWALAN PRODUKSI
 JENIS FLOWSHOP', False
,False
,False
,6);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (60,'1374766099', 2015, 2, 'IMPLEMENTASI ALGORITMA DIJKSTRA
 DENGAN PRINSIP GREEDY
  DALAM PENCARIAN RUTE TERPENDEK
 DARI SUATU KOTA KE TEMPAT PARIWISATA DI PULAU JAWA
 BERBASIS SISTEM INFORMASI GEOGRAFIS', False
,False
,False
,6);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (61,'1504126191', 2016, 1, 'PENERAPAN ALGORITMA LEVENSHTEIN DISTANCE PADA SPELLING CHECKER
 BAHASA INDONESIA', False
,False
,False
,3);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (62,'1324298936', 2015, 1, 'FILE MANAJEMEN PADA SERVER STUDENTS UKDW BERBASIS
 OBJECT ORIENTED PROGRAMMING MENGGUNAKAN PHP 5', False
,False
,False
,9);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (63,'1635501733', 2016, 2, 'DATA MINING UNTUK 
 MENDETEKSI KESEHATAN FISIK SESEORANG DENGAN ALGORITMA GROUP METHOD OF DATA HANDLING', False
,False
,False
,2);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (64,'1660919273', 2016, 2, 'IMPLEMENTASI NAIVE BAYESIAN CLASSIFIER PADA PROGRAM BANTU PENENTUAN BUKU REFERENSI MATAKULIAH', False
,False
,False
,6);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (65,'1229574307', 2016, 2, 'PROGRAM BANTU PENENTUAN KOTAK LO SHU PADA DENAH RUMAH DENGAN METODE OVERLAY
 (TUMPANG SUSUN)', False
,False
,False
,2);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (66,'1635617851', 2015, 1, 'IMPLEMENTASI DIRECTED ACYCLIC WORD GRAPH PADA WEB
 CRAWLER UNTUK INDEXING WEB', False
,False
,False
,1);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (67,'1274665705', 2016, 2, 'SISTEM PENDUKUNG KEPUTUSAN UNTUK SINYAL JUAL/BELI SAHAM MENGGUNAKAN METODE
 STOCHASTIC OSCILLATOR DAN BOLLINGER BANDS', False
,False
,False
,3);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (68,'1517284382', 2015, 2, 'PENERAPAN ALGORITMA SIMULATED ANNEALING PADA FACILITY LAYOUT PROBLEM', False
,False
,False
,5);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (69,'1672924140', 2015, 1, 'STATESKOP BERBASIS KOMPUTER', False
,False
,False
,8);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (70,'1408724210', 2016, 1, 'APLIKASI MOBILE NEWS', False
,False
,False
,4);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (71,'1531073781', 2016, 2, 'PENERAPAN TEORI KOGNITIF UNTUK MENINGKATKAN EFISIENSI PENGGUNAAN PROGRAM GENERATOR DATABASE
 BERBASIS WEB', False
,False
,False
,2);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (72,'1379044037', 2016, 2, 'VISUALISASI SUARA ULTRASONIK', False
,False
,False
,5);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (73,'1426212493', 2015, 1, 'APLIKASI ANIMASI CLIENT/SERVER BERBASIS WEB SERVICE', False
,False
,False
,9);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (74,'1471404579', 2016, 2, 'IMPLEMENTASI ADVANCED ENCRYPTION STANDARD (AES) DAN CIPHER BLOCK CHAINING (CBC) UNTUK
 ENKRIPSI DAN DEKRIPSI FILE TEXT', False
,False
,False
,3);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (75,'1195002084', 2015, 2, 'PENERAPAN ALGORITMA PINEDO
  MENGGUNAKAN METODE BRANCH AND BOUND UNTUK MENYELESAIKAN PERMASALAHAN JOB SHOP SCHEDULING', False
,False
,False
,5);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (76,'1167327851', 2016, 2, 'IMPLEMENTASI ALGORITMA PHYSICAL-A* (PHA*) UNTUK MENEMUKAN LINTASAN TERPENDEK', False
,False
,False
,4);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (77,'1324961184', 2016, 2, 'PENENTUAN FASE LALU LINTAS PADA PERSIMPANGAN DENGAN MENGGUNAKAN PENDEKATAN TEORI GRAF', False
,False
,False
,4);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (78,'1453761814', 2015, 1, 'PEMBUATAN SITUS WEB INTERAKTIF DENGAN SUARA MENGGUNAKAN VXML', False
,False
,False
,2);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (79,'1445078125', 2016, 2, 'PENDETEKSIAN WATERMARKING DALAM KARTU TANDA PENDUDUK (KTP) DENGAN MENGGUNAKAN PENAPIS LOLOS
 ATAS, LAPLACIAN, MEDIAN, DIRECTIONAL, GAUSSIAN, ROBERTS DAN SOBEL', False
,False
,False
,5);"
"INSERT INTO MATA_KULIAH_SPESIAL (IdMKS, NPM, Tahun, Semester, Judul, IsSiapSidang, PengumpulanHardCopy, IzinMajuSidang,  IdJenisMKS) VALUES (80,'1383339993', 2015, 2, 'APLIKASI GENERATOR SCRIPT
 BASIS DATA RELASIONAL BERBASIS OBYEK ORACLE 10g', False
,False
,False
,1);"